#!/usr/bin/env python3
"""
sync-claude-to-codex.py — One-way sync from Claude Code → Codex (AGENTS.md + config.toml).

Converts Claude Code's project state into Codex-readable format so that
when Codex is invoked, it knows what Claude has been doing.

What it syncs:
  CLAUDE.md (all levels)     → AGENTS.md (project root + ~/.codex/)
  settings.json              → config.toml (partial)
  auto-memory (key entries)  → AGENTS.md appendix
  learned skills             → AGENTS.md appendix

Usage:
    python sync-claude-to-codex.py                    # sync current workspace
    python sync-claude-to-codex.py --workspace <path> # sync specific workspace
    python sync-claude-to-codex.py --global            # sync global only
    python sync-claude-to-codex.py --dry-run           # preview without writing

Designed to run as a cron job (e.g., every 30 minutes).
No external dependencies — stdlib only.
"""

import argparse
import json
import os
import platform
import sys
from datetime import datetime, timezone
from pathlib import Path

# ── Paths ────────────────────────────────────────────────────────────────────

HOME = Path.home()
IS_WINDOWS = platform.system() == "Windows"

# Claude Code paths
CLAUDE_DIR = HOME / ".claude"
CLAUDE_GLOBAL_MD = CLAUDE_DIR / "CLAUDE.md"
CLAUDE_SETTINGS_GLOBAL = CLAUDE_DIR / "settings.json"

# Codex paths
CODEX_DIR = HOME / ".codex"
CODEX_GLOBAL_AGENTS = CODEX_DIR / "AGENTS.md"
CODEX_CONFIG_TOML = CODEX_DIR / "config.toml"


# ── Utilities ────────────────────────────────────────────────────────────────

def read_file(path: Path) -> str:
    if path.exists():
        try:
            return path.read_text(encoding="utf-8")
        except OSError:
            return ""
    return ""


def read_json(path: Path) -> dict:
    if path.exists():
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return {}
    return {}


def write_file(path: Path, content: str, dry_run: bool = False) -> bool:
    """Write file, creating parent dirs. Returns True if content changed."""
    existing = read_file(path)
    if existing.strip() == content.strip():
        return False  # no change

    if dry_run:
        print(f"  [DRY RUN] Would write: {path}")
        return True

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


# ── CLAUDE.md → AGENTS.md conversion ────────────────────────────────────────

AGENTS_HEADER = """# Project Instructions (synced from Claude Code)

> This file is auto-generated by `sync-claude-to-codex.py`.
> Source: Claude Code's CLAUDE.md + memory system.
> Last sync: {timestamp}
>
> **Do not edit manually** — changes will be overwritten on next sync.

---

"""

AGENTS_FOOTER = """

---

## Sync Metadata

- Source: Claude Code (CLAUDE.md + auto-memory)
- Synced: {timestamp}
- Tool: clawd-lobster/scripts/sync-claude-to-codex.py
"""


def convert_claude_md_to_agents_md(claude_md: str) -> str:
    """Convert CLAUDE.md content to AGENTS.md format.

    AGENTS.md is just Markdown — same as CLAUDE.md. The main conversion is:
    1. Strip Claude-specific meta (like hook configs, skill references)
    2. Add header noting this is auto-synced
    3. Reformat sections that reference Claude-specific tooling
    """
    if not claude_md.strip():
        return ""

    lines = claude_md.split("\n")
    output = []
    skip_section = False

    for line in lines:
        # Skip sections that are Claude-internal
        lower = line.lower().strip()
        if any(x in lower for x in [
            "## hooks",
            "## mcp servers",
            "## permission",
            "## session-memory hook",
            "## command-logger hook",
        ]):
            skip_section = True
            continue

        # Resume on next heading
        if skip_section and line.startswith("#"):
            skip_section = False

        if skip_section:
            continue

        # Replace Claude-specific references
        line = line.replace("Claude Code", "AI Agent")
        line = line.replace("claude code", "AI agent")
        line = line.replace("/spec", "spec workflow")
        line = line.replace("/evolve", "evolve workflow")

        output.append(line)

    return "\n".join(output)


# ── Memory → AGENTS.md appendix ─────────────────────────────────────────────

def gather_memory_context(workspace: Path | None) -> str:
    """Read Claude auto-memory and extract key project context for Codex."""
    sections = []

    # Find the matching memory directory
    if workspace:
        # Claude Code stores per-project memory in ~/.claude/projects/<path-hash>/memory/
        projects_dir = CLAUDE_DIR / "projects"
        if projects_dir.exists():
            for proj_dir in projects_dir.iterdir():
                memory_dir = proj_dir / "memory"
                if memory_dir.exists():
                    # Check if this project matches our workspace
                    # The directory name is a path hash, so check MEMORY.md content
                    memory_md = memory_dir / "MEMORY.md"
                    if memory_md.exists():
                        sections.append(_extract_memory_summary(memory_dir))
                        break

    if not sections:
        return ""

    return "\n## Project Context (from Claude Memory)\n\n" + "\n".join(sections)


def _extract_memory_summary(memory_dir: Path) -> str:
    """Extract a concise summary from memory files for AGENTS.md."""
    lines = []

    # Read MEMORY.md index
    index = read_file(memory_dir / "MEMORY.md")
    if not index:
        return ""

    # Extract key entries (skip status files, focus on architecture/feedback)
    for line in index.split("\n"):
        if not line.strip().startswith("- ["):
            continue

        # Prioritize: feedback, project architecture, core vision
        lower = line.lower()
        if any(x in lower for x in ["feedback_", "project_claw", "project_agent", "reference_arp"]):
            # Extract the description part
            if "—" in line:
                desc = line.split("—", 1)[1].strip()
                lines.append(f"- {desc}")

    if not lines:
        return ""

    return "Key decisions and constraints:\n" + "\n".join(lines[:20])  # cap at 20 entries


# ── Learned skills → AGENTS.md appendix ──────────────────────────────────────

def gather_learned_skills(workspace: Path | None) -> str:
    """Read learned skills and summarize for Codex."""
    if not workspace:
        return ""

    skills_dir = workspace / "skills" / "learned"
    if not skills_dir.exists():
        return ""

    skills = []
    for f in skills_dir.glob("*.md"):
        name = f.stem
        # Read first line as description
        content = read_file(f)
        first_line = content.split("\n")[0].strip("# ").strip() if content else name
        skills.append(f"- **{name}**: {first_line}")

    if not skills:
        return ""

    return "\n## Learned Skills\n\n" + "\n".join(skills)


# ── settings.json → config.toml (partial) ───────────────────────────────────

def generate_config_toml(settings: dict) -> str:
    """Convert relevant Claude Code settings to Codex config.toml format."""
    lines = [
        "# Codex config (partially synced from Claude Code settings)",
        f"# Last sync: {datetime.now(timezone.utc).isoformat()}",
        "",
    ]

    # Model preference
    lines.append("[model]")
    lines.append('# Default model for Codex tasks')
    lines.append('# model = "o3"')
    lines.append("")

    # Sandbox
    lines.append("[sandbox]")
    lines.append('# Default sandbox mode: read-only | workspace-write | danger-full-access')
    lines.append('default = "workspace-write"')
    lines.append("")

    # Features
    lines.append("[features]")
    lines.append("plugins = true")
    lines.append("multi_agent = true")
    lines.append("shell_tool = true")
    lines.append("# child_agents_md = true  # uncomment when stable")
    lines.append("")

    return "\n".join(lines) + "\n"


# ── Main sync logic ─────────────────────────────────────────────────────────

def sync_workspace(workspace: Path, dry_run: bool = False) -> dict:
    """Sync a workspace's Claude state to Codex. Returns summary."""
    summary = {"agents_md": False, "config_toml": False, "files_written": []}
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # 1. Find CLAUDE.md
    claude_md_path = workspace / "CLAUDE.md"
    claude_md = read_file(claude_md_path)

    # 2. Convert CLAUDE.md → AGENTS.md
    agents_content = AGENTS_HEADER.format(timestamp=timestamp)

    if claude_md:
        agents_content += convert_claude_md_to_agents_md(claude_md)
    else:
        agents_content += "*No CLAUDE.md found in workspace.*\n"

    # 3. Add memory context
    memory_ctx = gather_memory_context(workspace)
    if memory_ctx:
        agents_content += "\n" + memory_ctx

    # 4. Add learned skills
    skills_ctx = gather_learned_skills(workspace)
    if skills_ctx:
        agents_content += "\n" + skills_ctx

    # 5. Add footer
    agents_content += AGENTS_FOOTER.format(timestamp=timestamp)

    # 6. Enforce 32 KiB limit (Codex constraint)
    if len(agents_content.encode("utf-8")) > 32 * 1024:
        # Truncate memory/skills sections to fit
        agents_content = agents_content[:32 * 1024 - 200]
        agents_content += "\n\n> **Truncated** — exceeded 32 KiB Codex limit.\n"

    # 7. Write AGENTS.md to workspace
    agents_path = workspace / "AGENTS.md"
    if write_file(agents_path, agents_content, dry_run):
        summary["agents_md"] = True
        summary["files_written"].append(str(agents_path))

    return summary


def sync_global(dry_run: bool = False) -> dict:
    """Sync global Claude settings to Codex. Returns summary."""
    summary = {"global_agents": False, "config_toml": False, "files_written": []}
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # 1. Global CLAUDE.md → ~/.codex/AGENTS.md
    global_claude = read_file(CLAUDE_GLOBAL_MD)
    if global_claude:
        content = AGENTS_HEADER.format(timestamp=timestamp)
        content += convert_claude_md_to_agents_md(global_claude)
        content += AGENTS_FOOTER.format(timestamp=timestamp)

        if write_file(CODEX_GLOBAL_AGENTS, content, dry_run):
            summary["global_agents"] = True
            summary["files_written"].append(str(CODEX_GLOBAL_AGENTS))

    # 2. settings.json → config.toml (only if config.toml doesn't exist)
    if not CODEX_CONFIG_TOML.exists():
        settings = read_json(CLAUDE_SETTINGS_GLOBAL)
        toml_content = generate_config_toml(settings)
        if write_file(CODEX_CONFIG_TOML, toml_content, dry_run):
            summary["config_toml"] = True
            summary["files_written"].append(str(CODEX_CONFIG_TOML))

    return summary


# ── CLI ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Sync Claude Code state → Codex (AGENTS.md + config.toml)",
    )
    parser.add_argument("--workspace", "-w", help="Workspace path to sync")
    parser.add_argument("--global", "-g", dest="global_only", action="store_true",
                        help="Sync global settings only")
    parser.add_argument("--dry-run", action="store_true", help="Preview without writing")
    parser.add_argument("--quiet", "-q", action="store_true", help="No output unless errors")
    args = parser.parse_args()

    results = []

    # Global sync
    if args.global_only or not args.workspace:
        result = sync_global(dry_run=args.dry_run)
        results.append(("global", result))

    # Workspace sync
    if args.workspace:
        ws = Path(args.workspace).resolve()
        if not ws.exists():
            print(f"Error: workspace not found: {ws}", file=sys.stderr)
            return 1
        result = sync_workspace(ws, dry_run=args.dry_run)
        results.append((str(ws), result))
    elif not args.global_only:
        # Try to sync current directory if it has a CLAUDE.md
        cwd = Path.cwd()
        if (cwd / "CLAUDE.md").exists():
            result = sync_workspace(cwd, dry_run=args.dry_run)
            results.append((str(cwd), result))

    # Report
    if not args.quiet:
        for name, result in results:
            written = result.get("files_written", [])
            if written:
                print(f"Synced ({name}): {len(written)} files")
                for f in written:
                    print(f"  -> {f}")
            else:
                print(f"No changes ({name})")

    return 0


if __name__ == "__main__":
    sys.exit(main())
